name: Build Image

on:
  schedule:
    - cron: '35 21 * * 2'
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  GH_REPO: '${{ github.repository }}'

run: |
  echo "GH_REPO_LC=${GH_REPO,,}" >> ${GITHUB_ENV}

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Github Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Log into DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            cmptstks/phpmyadmin:v2
            cmptstks/phpmyadmin:latest
            ghcr.io/${{ GH_REPO_LC }}:v2
            ghcr.io/${{ GH_REPO_LC }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
